"""Add support for internal subtitles

Revision ID: ac11b95549f6
Revises: a34578f54dd2
Create Date: 2020-04-21 04:22:17.245502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac11b95549f6'
down_revision = 'a34578f54dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtitle', sa.Column('internal', sa.Boolean(), nullable=True))
    op.add_column('subtitle', sa.Column('internal_include', sa.Boolean(), nullable=True))
    op.add_column('subtitle', sa.Column('internal_streamidx', sa.Integer(), nullable=True))
    op.add_column('subtitle', sa.Column('title', sa.Text(), nullable=True))
    op.alter_column('video', 'default_subtitles',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'default_subtitles',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('subtitle', 'title')
    op.drop_column('subtitle', 'internal_streamidx')
    op.drop_column('subtitle', 'internal_include')
    op.drop_column('subtitle', 'internal')
    # ### end Alembic commands ###
