"""Fix issues with subtitles

Revision ID: e35d4dc93b87
Revises: 7bfdfed1f303
Create Date: 2020-04-23 02:56:18.895341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e35d4dc93b87'
down_revision = '7bfdfed1f303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtitle', 'internal',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('subtitle', 'internal_include',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('subtitle', 'orig_file',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('subtitle', 'encoded_file_name')
    op.alter_column('video', 'default_subtitles',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'default_subtitles',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('subtitle', sa.Column('encoded_file_name', mysql.TEXT(), nullable=False))
    op.alter_column('subtitle', 'orig_file',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('subtitle', 'internal_include',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('subtitle', 'internal',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
